/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils
} from 'ethers'
import type {
  FunctionFragment,
  Result,
  EventFragment
} from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue
} from './common'

export type OrderInfoStruct = {
  market: PromiseOrValue<string>
  trader: PromiseOrValue<string>
  nonce: PromiseOrValue<BigNumberish>
  deadline: PromiseOrValue<BigNumberish>
}

export type OrderInfoStructOutput = [string, string, BigNumber, BigNumber] & {
  market: string
  trader: string
  nonce: BigNumber
  deadline: BigNumber
}

export type GammaOrderStruct = {
  info: OrderInfoStruct
  pairId: PromiseOrValue<BigNumberish>
  entryTokenAddress: PromiseOrValue<string>
  tradeAmount: PromiseOrValue<BigNumberish>
  tradeAmountSqrt: PromiseOrValue<BigNumberish>
  marginAmount: PromiseOrValue<BigNumberish>
  hedgeInterval: PromiseOrValue<BigNumberish>
  sqrtPriceTrigger: PromiseOrValue<BigNumberish>
  maxSlippageTolerance: PromiseOrValue<BigNumberish>
  validatorAddress: PromiseOrValue<string>
  validationData: PromiseOrValue<BytesLike>
}

export type GammaOrderStructOutput = [
  OrderInfoStructOutput,
  BigNumber,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  string,
  string
] & {
  info: OrderInfoStructOutput
  pairId: BigNumber
  entryTokenAddress: string
  tradeAmount: BigNumber
  tradeAmountSqrt: BigNumber
  marginAmount: BigNumber
  hedgeInterval: BigNumber
  sqrtPriceTrigger: BigNumber
  maxSlippageTolerance: BigNumber
  validatorAddress: string
  validationData: string
}

export declare namespace IPredyPool {
  export type PayoffStruct = {
    perpEntryUpdate: PromiseOrValue<BigNumberish>
    sqrtEntryUpdate: PromiseOrValue<BigNumberish>
    sqrtRebalanceEntryUpdateUnderlying: PromiseOrValue<BigNumberish>
    sqrtRebalanceEntryUpdateStable: PromiseOrValue<BigNumberish>
    perpPayoff: PromiseOrValue<BigNumberish>
    sqrtPayoff: PromiseOrValue<BigNumberish>
  }

  export type PayoffStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    perpEntryUpdate: BigNumber
    sqrtEntryUpdate: BigNumber
    sqrtRebalanceEntryUpdateUnderlying: BigNumber
    sqrtRebalanceEntryUpdateStable: BigNumber
    perpPayoff: BigNumber
    sqrtPayoff: BigNumber
  }

  export type TradeResultStruct = {
    payoff: IPredyPool.PayoffStruct
    vaultId: PromiseOrValue<BigNumberish>
    fee: PromiseOrValue<BigNumberish>
    minMargin: PromiseOrValue<BigNumberish>
    averagePrice: PromiseOrValue<BigNumberish>
    sqrtTwap: PromiseOrValue<BigNumberish>
    sqrtPrice: PromiseOrValue<BigNumberish>
  }

  export type TradeResultStructOutput = [
    IPredyPool.PayoffStructOutput,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    payoff: IPredyPool.PayoffStructOutput
    vaultId: BigNumber
    fee: BigNumber
    minMargin: BigNumber
    averagePrice: BigNumber
    sqrtTwap: BigNumber
    sqrtPrice: BigNumber
  }

  export type VaultStatusStruct = {
    id: PromiseOrValue<BigNumberish>
    vaultValue: PromiseOrValue<BigNumberish>
    minMargin: PromiseOrValue<BigNumberish>
    oraclePrice: PromiseOrValue<BigNumberish>
    FeeAmount: DataType.FeeAmountStruct
  }

  export type VaultStatusStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    DataType.FeeAmountStructOutput
  ] & {
    id: BigNumber
    vaultValue: BigNumber
    minMargin: BigNumber
    oraclePrice: BigNumber
    FeeAmount: DataType.FeeAmountStructOutput
  }

  export type TradeParamsStruct = {
    pairId: PromiseOrValue<BigNumberish>
    vaultId: PromiseOrValue<BigNumberish>
    tradeAmount: PromiseOrValue<BigNumberish>
    tradeAmountSqrt: PromiseOrValue<BigNumberish>
    extraData: PromiseOrValue<BytesLike>
  }

  export type TradeParamsStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string
  ] & {
    pairId: BigNumber
    vaultId: BigNumber
    tradeAmount: BigNumber
    tradeAmountSqrt: BigNumber
    extraData: string
  }
}

export declare namespace ISettlement {
  export type SettlementDataStruct = {
    settlementContractAddress: PromiseOrValue<string>
    encodedData: PromiseOrValue<BytesLike>
  }

  export type SettlementDataStructOutput = [string, string] & {
    settlementContractAddress: string
    encodedData: string
  }
}

export declare namespace IFillerMarket {
  export type SignedOrderStruct = {
    order: PromiseOrValue<BytesLike>
    sig: PromiseOrValue<BytesLike>
  }

  export type SignedOrderStructOutput = [string, string] & {
    order: string
    sig: string
  }
}

export declare namespace GammaTradeMarket {
  export type UserPositionStruct = {
    vaultId: PromiseOrValue<BigNumberish>
    lastHedgedTime: PromiseOrValue<BigNumberish>
    hedgeInterval: PromiseOrValue<BigNumberish>
    lastHedgedSqrtPrice: PromiseOrValue<BigNumberish>
    sqrtPriceTrigger: PromiseOrValue<BigNumberish>
    maxSlippageTolerance: PromiseOrValue<BigNumberish>
  }

  export type UserPositionStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    vaultId: BigNumber
    lastHedgedTime: BigNumber
    hedgeInterval: BigNumber
    lastHedgedSqrtPrice: BigNumber
    sqrtPriceTrigger: BigNumber
    maxSlippageTolerance: BigNumber
  }
}

export declare namespace DataType {
  export type FeeAmountStruct = {
    feeAmountBase: PromiseOrValue<BigNumberish>
    feeAmountQuote: PromiseOrValue<BigNumberish>
  }

  export type FeeAmountStructOutput = [BigNumber, BigNumber] & {
    feeAmountBase: BigNumber
    feeAmountQuote: BigNumber
  }

  export type VaultStruct = {
    id: PromiseOrValue<BigNumberish>
    marginId: PromiseOrValue<string>
    owner: PromiseOrValue<string>
    recipient: PromiseOrValue<string>
    margin: PromiseOrValue<BigNumberish>
    openPosition: Perp.UserStatusStruct
  }

  export type VaultStructOutput = [
    BigNumber,
    string,
    string,
    string,
    BigNumber,
    Perp.UserStatusStructOutput
  ] & {
    id: BigNumber
    marginId: string
    owner: string
    recipient: string
    margin: BigNumber
    openPosition: Perp.UserStatusStructOutput
  }
}

export declare namespace Perp {
  export type PositionStatusStruct = {
    amount: PromiseOrValue<BigNumberish>
    entryValue: PromiseOrValue<BigNumberish>
  }

  export type PositionStatusStructOutput = [BigNumber, BigNumber] & {
    amount: BigNumber
    entryValue: BigNumber
  }

  export type SqrtPositionStatusStruct = {
    amount: PromiseOrValue<BigNumberish>
    entryValue: PromiseOrValue<BigNumberish>
    quoteRebalanceEntryValue: PromiseOrValue<BigNumberish>
    baseRebalanceEntryValue: PromiseOrValue<BigNumberish>
    entryTradeFee0: PromiseOrValue<BigNumberish>
    entryTradeFee1: PromiseOrValue<BigNumberish>
  }

  export type SqrtPositionStatusStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    amount: BigNumber
    entryValue: BigNumber
    quoteRebalanceEntryValue: BigNumber
    baseRebalanceEntryValue: BigNumber
    entryTradeFee0: BigNumber
    entryTradeFee1: BigNumber
  }

  export type UserStatusStruct = {
    pairId: PromiseOrValue<BigNumberish>
    rebalanceLastTickLower: PromiseOrValue<BigNumberish>
    rebalanceLastTickUpper: PromiseOrValue<BigNumberish>
    lastNumRebalance: PromiseOrValue<BigNumberish>
    perp: Perp.PositionStatusStruct
    sqrtPerp: Perp.SqrtPositionStatusStruct
    basePosition: ScaledAsset.UserStatusStruct
    stablePosition: ScaledAsset.UserStatusStruct
  }

  export type UserStatusStructOutput = [
    BigNumber,
    number,
    number,
    BigNumber,
    Perp.PositionStatusStructOutput,
    Perp.SqrtPositionStatusStructOutput,
    ScaledAsset.UserStatusStructOutput,
    ScaledAsset.UserStatusStructOutput
  ] & {
    pairId: BigNumber
    rebalanceLastTickLower: number
    rebalanceLastTickUpper: number
    lastNumRebalance: BigNumber
    perp: Perp.PositionStatusStructOutput
    sqrtPerp: Perp.SqrtPositionStatusStructOutput
    basePosition: ScaledAsset.UserStatusStructOutput
    stablePosition: ScaledAsset.UserStatusStructOutput
  }
}

export declare namespace ScaledAsset {
  export type UserStatusStruct = {
    positionAmount: PromiseOrValue<BigNumberish>
    lastFeeGrowth: PromiseOrValue<BigNumberish>
  }

  export type UserStatusStructOutput = [BigNumber, BigNumber] & {
    positionAmount: BigNumber
    lastFeeGrowth: BigNumber
  }
}

export interface GammaTradeMarketInterface extends utils.Interface {
  functions: {
    'execDeltaHedge(address,uint256,(address,bytes))': FunctionFragment
    'executeOrder((bytes,bytes),(address,bytes))': FunctionFragment
    'getUserPosition(address,uint256)': FunctionFragment
    'owner()': FunctionFragment
    'predyTradeAfterCallback((uint256,uint256,int256,int256,bytes),((int256,int256,int256,int256,int256,int256),uint256,int256,int256,int256,uint256,uint256))': FunctionFragment
    'quoteExecuteOrder(((address,address,uint256,uint256),uint64,address,int256,int256,int256,uint256,uint256,uint64,address,bytes),(address,bytes))': FunctionFragment
    'transferOwnership(address)': FunctionFragment
    'updateQuoteTokenMap(uint256)': FunctionFragment
    'updateWhitelistFiller(address)': FunctionFragment
    'userPositions(address,uint256)': FunctionFragment
    'whitelistFiller()': FunctionFragment
  }

  getFunction(
    nameOrSignatureOrTopic:
      | 'execDeltaHedge'
      | 'executeOrder'
      | 'getUserPosition'
      | 'owner'
      | 'predyTradeAfterCallback'
      | 'quoteExecuteOrder'
      | 'transferOwnership'
      | 'updateQuoteTokenMap'
      | 'updateWhitelistFiller'
      | 'userPositions'
      | 'whitelistFiller'
  ): FunctionFragment

  encodeFunctionData(
    functionFragment: 'execDeltaHedge',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      ISettlement.SettlementDataStruct
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'executeOrder',
    values: [IFillerMarket.SignedOrderStruct, ISettlement.SettlementDataStruct]
  ): string
  encodeFunctionData(
    functionFragment: 'getUserPosition',
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'predyTradeAfterCallback',
    values: [IPredyPool.TradeParamsStruct, IPredyPool.TradeResultStruct]
  ): string
  encodeFunctionData(
    functionFragment: 'quoteExecuteOrder',
    values: [GammaOrderStruct, ISettlement.SettlementDataStruct]
  ): string
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'updateQuoteTokenMap',
    values: [PromiseOrValue<BigNumberish>]
  ): string
  encodeFunctionData(
    functionFragment: 'updateWhitelistFiller',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'userPositions',
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string
  encodeFunctionData(
    functionFragment: 'whitelistFiller',
    values?: undefined
  ): string

  decodeFunctionResult(
    functionFragment: 'execDeltaHedge',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'executeOrder',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'getUserPosition',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'predyTradeAfterCallback',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'quoteExecuteOrder',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'updateQuoteTokenMap',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'updateWhitelistFiller',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'userPositions',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'whitelistFiller',
    data: BytesLike
  ): Result

  events: {
    'GammaPositionHedged(address,uint256,uint256,uint256,int256,tuple,int256)': EventFragment
    'GammaPositionTraded(address,uint256,uint256,uint256,uint256,tuple,int256,int256)': EventFragment
    'OwnershipTransferred(address,address)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'GammaPositionHedged'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'GammaPositionTraded'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment
}

export interface GammaPositionHedgedEventObject {
  trader: string
  pairId: BigNumber
  vaultId: BigNumber
  sqrtPrice: BigNumber
  delta: BigNumber
  payoff: IPredyPool.PayoffStructOutput
  fee: BigNumber
}
export type GammaPositionHedgedEvent = TypedEvent<
  [
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    IPredyPool.PayoffStructOutput,
    BigNumber
  ],
  GammaPositionHedgedEventObject
>

export type GammaPositionHedgedEventFilter =
  TypedEventFilter<GammaPositionHedgedEvent>

export interface GammaPositionTradedEventObject {
  trader: string
  pairId: BigNumber
  vaultId: BigNumber
  hedgeInterval: BigNumber
  sqrtPriceTrigger: BigNumber
  payoff: IPredyPool.PayoffStructOutput
  fee: BigNumber
  marginAmount: BigNumber
}
export type GammaPositionTradedEvent = TypedEvent<
  [
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    IPredyPool.PayoffStructOutput,
    BigNumber,
    BigNumber
  ],
  GammaPositionTradedEventObject
>

export type GammaPositionTradedEventFilter =
  TypedEventFilter<GammaPositionTradedEvent>

export interface OwnershipTransferredEventObject {
  user: string
  newOwner: string
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>

export interface GammaTradeMarket extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: GammaTradeMarketInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    execDeltaHedge(
      owner: PromiseOrValue<string>,
      pairId: PromiseOrValue<BigNumberish>,
      settlementData: ISettlement.SettlementDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    executeOrder(
      order: IFillerMarket.SignedOrderStruct,
      settlementData: ISettlement.SettlementDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    getUserPosition(
      owner: PromiseOrValue<string>,
      pairId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    owner(overrides?: CallOverrides): Promise<[string]>

    predyTradeAfterCallback(
      tradeParams: IPredyPool.TradeParamsStruct,
      tradeResult: IPredyPool.TradeResultStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    quoteExecuteOrder(
      gammaOrder: GammaOrderStruct,
      settlementData: ISettlement.SettlementDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    /**
     * Registers quote token address for the pair
     */
    updateQuoteTokenMap(
      pairId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    /**
     * only owner can call this function
     * Updates the whitelist filler address
     */
    updateWhitelistFiller(
      newWhitelistFiller: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    userPositions(
      owner: PromiseOrValue<string>,
      pairId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        vaultId: BigNumber
        lastHedgedTime: BigNumber
        hedgeInterval: BigNumber
        lastHedgedSqrtPrice: BigNumber
        sqrtPriceTrigger: BigNumber
        maxSlippageTolerance: BigNumber
      }
    >

    whitelistFiller(overrides?: CallOverrides): Promise<[string]>
  }

  execDeltaHedge(
    owner: PromiseOrValue<string>,
    pairId: PromiseOrValue<BigNumberish>,
    settlementData: ISettlement.SettlementDataStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  executeOrder(
    order: IFillerMarket.SignedOrderStruct,
    settlementData: ISettlement.SettlementDataStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  getUserPosition(
    owner: PromiseOrValue<string>,
    pairId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  owner(overrides?: CallOverrides): Promise<string>

  predyTradeAfterCallback(
    tradeParams: IPredyPool.TradeParamsStruct,
    tradeResult: IPredyPool.TradeResultStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  quoteExecuteOrder(
    gammaOrder: GammaOrderStruct,
    settlementData: ISettlement.SettlementDataStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  /**
   * Registers quote token address for the pair
   */
  updateQuoteTokenMap(
    pairId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  /**
   * only owner can call this function
   * Updates the whitelist filler address
   */
  updateWhitelistFiller(
    newWhitelistFiller: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  userPositions(
    owner: PromiseOrValue<string>,
    pairId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      vaultId: BigNumber
      lastHedgedTime: BigNumber
      hedgeInterval: BigNumber
      lastHedgedSqrtPrice: BigNumber
      sqrtPriceTrigger: BigNumber
      maxSlippageTolerance: BigNumber
    }
  >

  whitelistFiller(overrides?: CallOverrides): Promise<string>

  callStatic: {
    execDeltaHedge(
      owner: PromiseOrValue<string>,
      pairId: PromiseOrValue<BigNumberish>,
      settlementData: ISettlement.SettlementDataStruct,
      overrides?: CallOverrides
    ): Promise<IPredyPool.TradeResultStructOutput>

    executeOrder(
      order: IFillerMarket.SignedOrderStruct,
      settlementData: ISettlement.SettlementDataStruct,
      overrides?: CallOverrides
    ): Promise<IPredyPool.TradeResultStructOutput>

    getUserPosition(
      owner: PromiseOrValue<string>,
      pairId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        GammaTradeMarket.UserPositionStructOutput,
        IPredyPool.VaultStatusStructOutput,
        DataType.VaultStructOutput
      ] & { userPosition: GammaTradeMarket.UserPositionStructOutput }
    >

    owner(overrides?: CallOverrides): Promise<string>

    predyTradeAfterCallback(
      tradeParams: IPredyPool.TradeParamsStruct,
      tradeResult: IPredyPool.TradeResultStruct,
      overrides?: CallOverrides
    ): Promise<void>

    quoteExecuteOrder(
      gammaOrder: GammaOrderStruct,
      settlementData: ISettlement.SettlementDataStruct,
      overrides?: CallOverrides
    ): Promise<void>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>

    /**
     * Registers quote token address for the pair
     */
    updateQuoteTokenMap(
      pairId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>

    /**
     * only owner can call this function
     * Updates the whitelist filler address
     */
    updateWhitelistFiller(
      newWhitelistFiller: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>

    userPositions(
      owner: PromiseOrValue<string>,
      pairId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        vaultId: BigNumber
        lastHedgedTime: BigNumber
        hedgeInterval: BigNumber
        lastHedgedSqrtPrice: BigNumber
        sqrtPriceTrigger: BigNumber
        maxSlippageTolerance: BigNumber
      }
    >

    whitelistFiller(overrides?: CallOverrides): Promise<string>
  }

  filters: {
    'GammaPositionHedged(address,uint256,uint256,uint256,int256,tuple,int256)'(
      trader?: PromiseOrValue<string> | null,
      pairId?: null,
      vaultId?: null,
      sqrtPrice?: null,
      delta?: null,
      payoff?: null,
      fee?: null
    ): GammaPositionHedgedEventFilter
    GammaPositionHedged(
      trader?: PromiseOrValue<string> | null,
      pairId?: null,
      vaultId?: null,
      sqrtPrice?: null,
      delta?: null,
      payoff?: null,
      fee?: null
    ): GammaPositionHedgedEventFilter

    'GammaPositionTraded(address,uint256,uint256,uint256,uint256,tuple,int256,int256)'(
      trader?: PromiseOrValue<string> | null,
      pairId?: null,
      vaultId?: null,
      hedgeInterval?: null,
      sqrtPriceTrigger?: null,
      payoff?: null,
      fee?: null,
      marginAmount?: null
    ): GammaPositionTradedEventFilter
    GammaPositionTraded(
      trader?: PromiseOrValue<string> | null,
      pairId?: null,
      vaultId?: null,
      hedgeInterval?: null,
      sqrtPriceTrigger?: null,
      payoff?: null,
      fee?: null,
      marginAmount?: null
    ): GammaPositionTradedEventFilter

    'OwnershipTransferred(address,address)'(
      user?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter
    OwnershipTransferred(
      user?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter
  }

  estimateGas: {
    execDeltaHedge(
      owner: PromiseOrValue<string>,
      pairId: PromiseOrValue<BigNumberish>,
      settlementData: ISettlement.SettlementDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    executeOrder(
      order: IFillerMarket.SignedOrderStruct,
      settlementData: ISettlement.SettlementDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    getUserPosition(
      owner: PromiseOrValue<string>,
      pairId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    owner(overrides?: CallOverrides): Promise<BigNumber>

    predyTradeAfterCallback(
      tradeParams: IPredyPool.TradeParamsStruct,
      tradeResult: IPredyPool.TradeResultStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    quoteExecuteOrder(
      gammaOrder: GammaOrderStruct,
      settlementData: ISettlement.SettlementDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    /**
     * Registers quote token address for the pair
     */
    updateQuoteTokenMap(
      pairId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    /**
     * only owner can call this function
     * Updates the whitelist filler address
     */
    updateWhitelistFiller(
      newWhitelistFiller: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    userPositions(
      owner: PromiseOrValue<string>,
      pairId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    whitelistFiller(overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    execDeltaHedge(
      owner: PromiseOrValue<string>,
      pairId: PromiseOrValue<BigNumberish>,
      settlementData: ISettlement.SettlementDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    executeOrder(
      order: IFillerMarket.SignedOrderStruct,
      settlementData: ISettlement.SettlementDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    getUserPosition(
      owner: PromiseOrValue<string>,
      pairId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>

    predyTradeAfterCallback(
      tradeParams: IPredyPool.TradeParamsStruct,
      tradeResult: IPredyPool.TradeResultStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    quoteExecuteOrder(
      gammaOrder: GammaOrderStruct,
      settlementData: ISettlement.SettlementDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    /**
     * Registers quote token address for the pair
     */
    updateQuoteTokenMap(
      pairId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    /**
     * only owner can call this function
     * Updates the whitelist filler address
     */
    updateWhitelistFiller(
      newWhitelistFiller: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    userPositions(
      owner: PromiseOrValue<string>,
      pairId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    whitelistFiller(overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
